### ISSUE TITLE
Combo point

### ISSUE THREAD

**Issue by SirLagardere** [Gendr/HideBlizzard#1]
Hi,
It seems that hiding combo point on the player frame is not persistent (login, zoning and back from possess special mobs)
Thanks for your help
Regards

**Comment by Gendr** [comment]
This should fix it, just delete and copy this new Player.lua file into the "modules" folder. Thank you
[Player.zip](https://github.com/Gendr/HideBlizzard/files/3572435/Player.zip)

**Comment by SirLagardere** [comment]
Thanks, I've tried the new file, but the problem still persist.
On the other side hiding the player castbar is persistent.

**Comment by Gendr** [comment]
That's odd. Enabling "Combo Bar" option while zoning, shifting forms, or reloding UI will keep the bar hidden for me..

**Comment by SirLagardere** [comment]
I've tried on a druid and that works perfectly, but on my rogue it's a no go :(

**Comment by Gendr** [comment]
This has now been fixed. Please delete and copy this new Player.lua file into the "modules" folder. Thank you
[Player.zip](https://github.com/Gendr/HideBlizzard/files/3576422/Player.zip)
